### ISSUE TITLE
✅ Write unit tests

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/pure-fun#1]

**Comment by thibmaek** [comment]
Hi Hacktoberfest contributors!

This one is a really easy one for javascript developers! This repo consists of very localised and simple pure functions that do not modify their values and just return new data.

But of course to rely on this set, it needs some unit testing to make sure nothing breaks.
`jest` is already in the devDependencies so basically it only needs some simple assertions to test these utils!

**Comment by colmose** [comment]
I can jump on this over the next few days. Haven't had a chance to play around with Jest yet.

**Comment by thibmaek** [comment]
@colmose That's OK! Jest is very much like Jasmine (actually based on it) or Mocha.

**Comment by colmose** [comment]
Had a bit of a read of the matchers, etc recently but there's nothing like taking it out for a spin!
