### ISSUE TITLE
Check failing test for async/sleep

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/pure-fun#10]

**Comment by Rende11** [comment]
May be should round 499 ms to 500 ?

**Comment by abhishek1nair** [comment]
@thibmaek do you write failure cases? since on running locally all tests are passing

**Comment by abhishek1nair** [comment]
@thibmaek I don't think checking for exact time is a good idea, but we can keep a error margin like between 500 ms and 502 ms, something like that.

**Comment by thibmaek** [comment]
Closed with #13
