### ISSUE TITLE
Use babel-preset-env for node in tests

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/pure-fun#11]
https://babeljs.io/docs/plugins/preset-env/

> For convenience, you can use "node": "current" to only include the necessary polyfills and transforms for the Node.js version that you use to run Babel:

**Comment by sophiekoonin** [comment]
Happy to take this on but I can't see where you've actually used babel? There's no .babelrc that I can see.

**Comment by thibmaek** [comment]
@sophiekoonin There is a .babelrc in project root for having import/export available in jest (used for testing). It currently uses es-2015 & es-2017 but should thus be replaced with preset-env for node:current

**Comment by sophiekoonin** [comment]
@thibmaek so there is... my `ls` didn't pick it up!

**Comment by thibmaek** [comment]
Prob need to do `ls -a` to be able to see a dotfile ;)

**Comment by sophiekoonin** [comment]
Yep... figured that out. Too hungry to concentrate :)
