### ISSUE TITLE
Set up release automation

### ISSUE THREAD

**Issue by thibmaek** [thibmaek/pure-fun#5]
This project should be able to release for every new merge or commit on master.
Think `@sindresorhus/np` so it publishes to npmjs.org registry

**Comment by abhishek1nair** [comment]
@thibmaek do you want to automatically publish to npm when travis passes?

**Comment by thibmaek** [comment]
That would be really handy!

**Comment by thibmaek** [comment]
https://docs.travis-ci.com/user/deployment/npm/
